basePath: /api/v1
info:
  contact: {}
  description: This is the v1 of the API
  title: Example API v1
  version: "1.0"
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      summary: test api
      tags:
        - internal
swagger: "2.0"
